version: '3'
services:
    nginx:
        image: nginx:alpine
        volumes:
            - ./src/:/var/www/event-tracker
            - ./docker/nginx/ssl:/etc/nginx/ssl
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - "8080:443"
        links:
            - php-fpm
    php-fpm:
        build:
            context: ./
            dockerfile: docker/php-fpm.docker
        volumes:
            - ./src/:/var/www/event-tracker
#        links:
#            - mysql
#            - redis
#        environment:
#            - "DB_PORT=3306"
#            - "DB_HOST=mysql"
#            - "REDIS_PORT=6379"
#            - "REDIS_HOST=redis"
    node:
        image: node:alpine
        volumes:
            - ./src/:/var/www/event-tracker
        working_dir: /var/www/event-tracker
        tty: true