services:
    nginx:
        image: nginx:alpine
        volumes:
            - ./src/:/var/www/event-tracker
            - ./docker/nginx/ssl:/etc/nginx/ssl
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - "8080:443"
        depends_on:
            - php-fpm
        networks:
            - app_network
    php-fpm:
        build:
            context: ./
            dockerfile: docker/php-fpm.dockerfile
        volumes:
            - ./src/:/var/www/event-tracker
        depends_on:
            - mysql
            - redis
        environment:
#            - "DB_PORT=3306"
#            - "DB_HOST=mysql"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=redis"
        networks:
            - app_network
    php-cli:
        build:
            context: ./
            dockerfile: docker/php-cli.dockerfile
        volumes:
            - ./src/:/var/www/event-tracker
        depends_on:
            - mysql
            - redis
#        environment:
#            - "DB_PORT=3306"
#            - "DB_HOST=mysql"
#            - "REDIS_PORT=6379"
#            - "REDIS_HOST=redis"
        tty: true
        networks:
            - app_network
    mysql:
        image: mysql:latest
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "app"
            MYSQL_PASSWORD: "app"
            MYSQL_DATABASE: "eventtracker"
        ports:
            - "33061:3306"
        networks:
            - app_network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: "root"
        ports:
            - "8090:80"
        networks:
            - app_network
    node:
        image: node:alpine
        volumes:
            - ./src/:/var/www/event-tracker
        working_dir: /var/www/event-tracker
        ports:
            - "3009:3009"
        tty: true
    redis:
        image: redis:latest
        ports:
            - 6379:6379
        restart: always
        command: redis-server --save 20 1 --loglevel warning
        volumes:
            - ./redis/data:/data
        networks:
            - app_network
    redisinsight:
        image: redislabs/redisinsight:latest
        ports:
          - '5540:5540'
        volumes:
          - ./redis/insight:/db
        depends_on:
            - redis
        networks:
            - app_network
    supervisor:
        build:
            context: ./
            dockerfile: docker/supervisor.dockerfile
        ports:
            - "9001:9001"
        volumes:
            - ./src/:/var/www/event-tracker
        depends_on:
            - php-cli
            - redis
        networks:
            - app_network
networks:
    app_network:
        driver: bridge